### PR TITLE
Don't leak the viewport subscription when the viewport data is read

### LINKED ISSUE #4406: MessageDeframer NullPointerException
Found in the [Web UI e2e tests](https://github.com/deephaven/web-client-ui/issues/1466) while running rollup tests. Intermittently occurred causing a brief disconnect, which would cause e2e tests to blip and fail. The cause/NullPointerException details were found by adding extra logging, as there isn't [logging in this particular case](https://github.com/deephaven/deephaven-core/blob/84199c76c835ee0f1b1032c8f4c8b17ab4d15732/grpc-java/grpc-servlet-websocket-jakarta/src/main/java/io/grpc/servlet/web/websocket/MultiplexedWebsocketStreamImpl.java#L113) to prevent an infinite loop with the logger stream.

```
2023-08-29 14:54:16 2023-08-29T18:54:16.013Z | qtp880533231-33      |  WARN | plexedWebsocketStreamImpl | MJB MultiplexedWebsocketStreamImpl cancel: Status{code=UNKNOWN, description=null, cause=java.lang.NullPointerException: Cannot invoke "io.grpc.internal.CompositeReadableBuffer.readableBytes()" because "this.unprocessed" is null
2023-08-29 14:54:16     at io.grpc.internal.MessageDeframer.readRequiredBytes(MessageDeframer.java:346)
2023-08-29 14:54:16     at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:269)
2023-08-29 14:54:16     at io.grpc.internal.MessageDeframer.deframe(MessageDeframer.java:178)
2023-08-29 14:54:16     at io.grpc.internal.AbstractStream$TransportState.deframe(AbstractStream.java:210)
2023-08-29 14:54:16     at io.grpc.internal.AbstractServerStream$TransportState.inboundDataReceived(AbstractServerStream.java:262)
2023-08-29 14:54:16     at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl$WebsocketTransportState.inboundDataReceived(AbstractWebsocketStreamImpl.java:25)
2023-08-29 14:54:16     at io.grpc.servlet.web.websocket.AbstractWebsocketStreamImpl.inboundDataReceived(AbstractWebsocketStreamImpl.java:99)
2023-08-29 14:54:16     at io.grpc.servlet.web.websocket.MultiplexedWebSocketServerStream.onMessage(MultiplexedWebSocketServerStream.java:219)
2023-08-29 14:54:16     at io.grpc.servlet.web.websocket.AbstractWebSocketServerStream.lambda$onOpen$0(AbstractWebSocketServerStream.java:115)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink.invoke(AbstractDecodedMessageSink.java:61)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.jakarta.common.messages.DecodedBinaryMessageSink.onWholeMessage(DecodedBinaryMessageSink.java:60)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.messages.ByteBufferMessageSink.accept(ByteBufferMessageSink.java:64)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.jakarta.common.messages.AbstractDecodedMessageSink.accept(AbstractDecodedMessageSink.java:80)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.acceptMessage(JakartaWebSocketFrameHandler.java:592)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onBinary(JakartaWebSocketFrameHandler.java:642)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.jakarta.common.JakartaWebSocketFrameHandler.onFrame(JakartaWebSocketFrameHandler.java:243)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.lambda$onFrame$1(WebSocketCoreSession.java:671)
2023-08-29 14:54:16     at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1466)
2023-08-29 14:54:16     at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1485)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:212)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession$IncomingAdaptor.onFrame(WebSocketCoreSession.java:671)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.AbstractExtension.nextIncomingFrame(AbstractExtension.java:145)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.nextIncomingFrame(PerMessageDeflateExtension.java:236)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.emitFrame(DemandingFlusher.java:145)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.inflate(PerMessageDeflateExtension.java:480)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension$IncomingFlusher.handle(PerMessageDeflateExtension.java:413)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.process(DemandingFlusher.java:169)
2023-08-29 14:54:16     at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:243)
2023-08-29 14:54:16     at org.eclipse.jetty.util.IteratingCallback.succeeded(IteratingCallback.java:369)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.DemandingFlusher.onFrame(DemandingFlusher.java:104)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.PerMessageDeflateExtension.onFrame(PerMessageDeflateExtension.java:93)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.ExtensionStack.onFrame(ExtensionStack.java:120)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onFrame(WebSocketCoreSession.java:481)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFrame(WebSocketConnection.java:262)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.fillAndParse(WebSocketConnection.java:455)
2023-08-29 14:54:16     at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onFillable(WebSocketConnection.java:340)
2023-08-29 14:54:16     at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
2023-08-29 14:54:16     at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
2023-08-29 14:54:16     at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
2023-08-29 14:54:16     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
2023-08-29 14:54:16     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
2023-08-29 14:54:16     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
2023-08-29 14:54:16     at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
2023-08-29 14:54:16     at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
2023-08-29 14:54:16     at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
2023-08-29 14:54:16     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
2023-08-29 14:54:16     at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
2023-08-29 14:54:16     at java.base/java.lang.Thread.run(Thread.java:833)
2023-08-29 14:54:16 }
```

### LINKED ISSUE #4410: JS API getViewportData does not cleanup websocket listeners on table close
**Description**

When using the JS API, if I have a table and do `table.setViewport(0, 1)` followed by `const data = await table.getViewportData()` then the event listeners attached by `setViewport` do not get cleaned up when the table is closed.

**Steps to reproduce**
1. `table.setViewport(0, 1)`
2. `const data = await table.getViewportData()`
3. `table.close()`

**Expected results**

Table and viewport listeners are removed from the multiplexed websocket.

**Actual results**

Table listeners are removed, viewport listeners remain on multiplexed websocket.

**Additional details and attachments**

If I assign a variable to the `setViewport` call I can then close that viewport explicitly.

If I listen on table updated events instead of calling `getViewportData` then the listeners cleanup after themselves.

### PR DESCRIPTION
**Pull request by niloc132**
Fixes #4410

### CODE REVIEW

**Review by mattrunyon — APPROVED** [review]
Looks like it's working properly in the docs snapshots

**Comment by niloc132** [comment]
This is on hold to address a few other leaks as well.

**Review by mattrunyon — APPROVED** [review]
Should this close #4410?

Tested w/ docs snapshot tool by undoing the mitigations I had put in.

Confirmed w/ latest docker image the number of listeners grows unbounded by creating my own class extending `ws` which increments/decrements on `newListener` and `removeListener`.

With this change, number of listeners was not growing and stayed at a consistent overhead of 12 even after closing/re-opening the connection.

**Comment by niloc132** [comment]
Fixed the linked issue, thanks.

**Pull request merged**
