### PR TITLE
Set `NULL_CHAR` to `MAX_VALUE`.

### PR DESCRIPTION
**Pull request by chipkent**
A few query constants have unusual values.  This PR sets more rational values.

* Set NULL_CHAR to MAX_VALUE.

### CODE REVIEW

**Review by mofojed — CHANGES_REQUESTED** [review]
Need to update `ColumnValueDehydrater` as well: https://github.com/deephaven/deephaven-core/blob/92f67ecfbe4fdee2e0d3c0a4f59b5afaaf3f1398/web/client-api/src/main/java/io/deephaven/web/client/api/input/ColumnValueDehydrater.java#L114

**Comment by rcaudy** [comment]
We need to be sure to write and re-read some parquet data with three types of columns:
1. `char`
2. `char[]`
3. `DbCharArray`
Containing null and non-null values. We need to write with the old code and read back with the new and make sure we get the same results.

**Review by mofojed — APPROVED** [review]

**Review by hythloda — APPROVED** [review]

**Review by hythloda — CHANGES_REQUESTED** [review]
On further testing. I got an error in reading the parquet file in this fork.

**Comment by chipkent** [comment]
@hythloda : @rcaudy  and I were talking about the test for the PR.  We think that we need two changes to get a clean test.
* run the data generation using the current main code and then do the import using this branch.  Basically split the test into two pieces to confirm that data written with the old code can be loaded correctly in the new code.
* Our null value assumes people aren't doing unprintable characters like chr(65534).  Can you make sure that all values in the test are printable?

**Comment by chipkent** [comment]
I was able to run without exception using:
```
from deephaven.TableTools import newTable, charCol, col
from deephaven.conversion_utils import NULL_CHAR

myCharacters = ['a', 'b', chr(99), chr(100)]
myCharacters_null = [chr(NULL_CHAR), chr(127), NULL_CHAR, chr(6553)]

source = newTable( \
    col("object", ['a', 'b', chr(99), chr(100)], [chr(NULL_CHAR), chr(127), NULL_CHAR, chr(6553)], myCharacters, myCharacters_null), \
    charCol("char1" , myCharacters), \
    charCol("char2", None,chr(127),"c",chr(NULL_CHAR)),\
    charCol("char3",  chr(NULL_CHAR),chr(126),chr(127), chr(NULL_CHAR)),
    )

from deephaven.ParquetTools import writeTable

meta= source.getMeta()
writeTable(source, "/data/output_GZIP.parquet", "GZIP")
writeTable(source, "/data/output.parquet")
writeTable(source, "/data/output_LZ4.parquet", "LZ4")

from deephaven.ParquetTools import readTable
source2 = readTable("/data/output.parquet")
source3 = readTable("/data/output_LZ4.parquet", "LZ4")
source1 = readTable("/data/output_GZIP.parquet", "GZIP")

meta1 = source1.getMeta()
meta2 = source2.getMeta()
meta3 = source3.getMeta()
```

Actually, even the original code worked fine.

**Comment by jcferretti** [comment]
> On further testing. I got an error in reading the parquet file in this fork.
> 
> Here is the code I used that did not read in the new version:
> 
> ```
> from deephaven.TableTools import newTable, charCol, col
> from deephaven.conversion_utils import NULL_CHAR
> 
> myCharacters = ['a', 'b', chr(99), chr(100)]
> myCharacters_null = [chr(NULL_CHAR), chr(127), NULL_CHAR, chr(65534)]
> 
> source = newTable( \
>     col("object", ['a', 'b', chr(99), chr(100)], [chr(NULL_CHAR), chr(127), NULL_CHAR, chr(65534)], myCharacters, myCharacters_null), \
>     charCol("char1" , myCharacters), \
>     charCol("char2", None,chr(127),"c",chr(NULL_CHAR)),\
>     charCol("char3",  chr(NULL_CHAR),chr(126),chr(127), chr(NULL_CHAR)),
>     )
> 
> from deephaven.ParquetTools import writeTable
> 
> meta= source.getMeta()
> writeTable(source, "/data/output_GZIP.parquet", "GZIP")
> writeTable(source, "/data/output.parquet")
> writeTable(source, "/data/output_LZ4.parquet", "LZ4")
> 
> from deephaven.ParquetTools import readTable
> source2 = readTable("/data/output.parquet")
> source3 = readTable("/data/output_LZ4.parquet", "LZ4")
> source1 = readTable("/data/output_GZIP.parquet", "GZIP")
> 
> meta1 = source1.getMeta()
> meta2 = source2.getMeta()
> meta3 = source3.getMeta()
> ```
> 
> ```
> r-Scheduler-Serial-1 | i.d.g.s.SessionState      | Internal Error '004e15e2-00fd-4d6f-bd31-072bd6f83807' java.lang.RuntimeException: Error in Python interpreter:
> Type: <class 'RuntimeError'>
> Value: java.lang.RuntimeException: /data/output_GZIP.parquet is not a Parquet file. expected magic number at tail [80, 65, 82, 49] but found [0, 28, 0, 0]
> 	at io.deephaven.parquet.ParquetFileReader.<init>(ParquetFileReader.java:67)
> 	at io.deephaven.db.tables.utils.ParquetTools.getParquetFileReader(ParquetTools.java:612)
> 	at io.deephaven.db.v2.locations.parquet.local.ParquetTableLocationKey.getFileReader(ParquetTableLocationKey.java:69)
> 	at io.deephaven.db.tables.utils.ParquetTools.readTableInternal(ParquetTools.java:387)
> 	at io.deephaven.db.tables.utils.ParquetTools.readTable(ParquetTools.java:127)
> 	at org.jpy.PyLib.executeCode(Native Method)
> 	at org.jpy.PyObject.executeCode(PyObject.java:138)
> 	at io.deephaven.db.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:56)
> 	at io.deephaven.db.util.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:178)
> 	at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:46)
> 	at io.deephaven.db.util.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:177)
> 	at io.deephaven.db.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:108)
> 	at io.deephaven.db.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:71)
> 	at io.deephaven.db.util.ScriptSession.evaluateScript(ScriptSession.java:79)
> 	at io.deephaven.grpc_api.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:188)
> 	at io.deephaven.grpc_api.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1273)
> 	at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:825)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:147)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> 
> Line: 99
> Namespace: _custom_readTable
> File: /usr/local/lib/python3.7/dist-packages/deephaven/ParquetTools/__init__.py
> Traceback (most recent call last):
>   File "<string>", line 2, in <module>
>   File "/usr/local/lib/python3.7/dist-packages/deephaven/ParquetTools/__init__.py", line 62, in _passThrough
>   File "/usr/local/lib/python3.7/dist-packages/deephaven/ParquetTools/__init__.py", line 259, in readTable
>   File "/usr/local/lib/python3.7/dist-packages/deephaven/ParquetTools/__init__.py", line 99, in _custom_readTable
> 
>         at org.jpy.PyLib.executeCode(PyLib.java:-2)
>         at org.jpy.PyObject.executeCode(PyObject.java:138)
>         at io.deephaven.db.util.PythonEvaluatorJpy.evalScript(PythonEvaluatorJpy.java:56)
>         at io.deephaven.db.util.PythonDeephavenSession.lambda$evaluate$1(PythonDeephavenSession.java:178)
>         at io.deephaven.util.locks.FunctionalLock.doLockedInterruptibly(FunctionalLock.java:46)
>         at io.deephaven.db.util.PythonDeephavenSession.evaluate(PythonDeephavenSession.java:177)
>         at io.deephaven.db.util.AbstractScriptSession.evaluateScript(AbstractScriptSession.java:108)
>         at io.deephaven.db.util.DelegatingScriptSession.evaluateScript(DelegatingScriptSession.java:71)
>         at io.deephaven.db.util.ScriptSession.evaluateScript(ScriptSession.java:79)
>         at io.deephaven.grpc_api.console.ConsoleServiceGrpcImpl.lambda$executeCommand$8(ConsoleServiceGrpcImpl.java:188)
>         at io.deephaven.grpc_api.session.SessionState$ExportBuilder.lambda$submit$2(SessionState.java:1273)
>         at io.deephaven.grpc_api.session.SessionState$ExportObject.doExport(SessionState.java:825)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:264)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
>         at io.deephaven.grpc_api.runner.DeephavenApiServerModule$ThreadFactory.lambda$newThread$0(DeephavenApiServerModule.java:147)
>         at java.lang.Thread.run(Thread.java:833)
>         ```
> ```

This exception looks like, when that parquet file was generated, the writing got interrupted / cut short before finishing.  I'd be interested to know if the code that generated this file was a silent fail (bad) or some exception was produced (but maybe not noticed?).  Do we still have this file around?

**Comment by chipkent** [comment]
I created scripts to test null behavior in Parquet between main and this branch.

To write data from main:
```
from deephaven.TableTools import newTable, charCol, col
from deephaven.conversion_utils import NULL_CHAR

myCharacters = ['a', 'b', chr(99), chr(100)]
myCharacters_null = [chr(NULL_CHAR), chr(38), NULL_CHAR, chr(39)]

source = newTable( \
    col("object", ['a', 'b', chr(38), chr(39)], [chr(NULL_CHAR), chr(40), chr(NULL_CHAR), chr(41)], myCharacters, myCharacters_null), \
    charCol("char1" , myCharacters), \
    charCol("char2", None, chr(38), "c", chr(NULL_CHAR)),\
    charCol("char3",  chr(NULL_CHAR), chr(39), chr(40), chr(NULL_CHAR)),
    )

meta= source.getMeta()

from deephaven.ParquetTools import writeTable
writeTable(source, "/data/output.parquet")
writeTable(source, "/data/output_GZIP.parquet", "GZIP")
writeTable(source, "/data/output_LZ4.parquet", "LZ4")

from deephaven.ParquetTools import readTable
source2 = readTable("/data/output.parquet")
source3 = readTable("/data/output_LZ4.parquet", "LZ4")
source1 = readTable("/data/output_GZIP.parquet", "GZIP")

print("Check0a: ", source.getColumn("char2").getDirect()[0])
print("Check1a: ", source1.getColumn("char2").getDirect()[0])
print("Check2a: ", source2.getColumn("char2").getDirect()[0])
print("Check3a: ", source3.getColumn("char2").getDirect()[0])

print("Check0b: ", source.getColumn("char3").getDirect()[0])
print("Check1b: ", source1.getColumn("char3").getDirect()[0])
print("Check2b: ", source2.getColumn("char3").getDirect()[0])
print("Check3b: ", source3.getColumn("char3").getDirect()[0])

print("Check0c: ", ord(source.getColumn("object").getDirect()[1][0]))
print("Check1c: ", ord(source1.getColumn("object").getDirect()[1][0]))
print("Check2c: ", ord(source2.getColumn("object").getDirect()[1][0]))
print("Check3c: ", ord(source3.getColumn("object").getDirect()[1][0]))

meta1 = source1.getMeta()
meta2 = source2.getMeta()
meta3 = source3.getMeta()
```

To read the data back in on this branch:
```
from deephaven.TableTools import newTable, charCol, col
from deephaven.conversion_utils import NULL_CHAR

myCharacters = ['a', 'b', chr(99), chr(100)]
myCharacters_null = [NULL_CHAR, chr(38), ord(NULL_CHAR), chr(39)]

source = newTable( \
    col("object", ['a', 'b', chr(38), chr(39)], [NULL_CHAR, chr(40), NULL_CHAR, chr(41)], myCharacters, myCharacters_null), \
    charCol("char1" , myCharacters), \
    charCol("char2", None, chr(38), "c", NULL_CHAR),\
    charCol("char3",  NULL_CHAR, chr(39), chr(40), NULL_CHAR),
    )

meta= source.getMeta()

# from deephaven.ParquetTools import writeTable
# writeTable(source, "/data/output_GZIP.parquet", "GZIP")
# writeTable(source, "/data/output.parquet")
# writeTable(source, "/data/output_LZ4.parquet", "LZ4")

from deephaven.ParquetTools import readTable
source1 = readTable("/data/output.parquet")
source2 = readTable("/data/output_LZ4.parquet", "LZ4")
source3 = readTable("/data/output_GZIP.parquet", "GZIP")

print("Check0a: ", source.getColumn("char2").getDirect()[0])
print("Check1a: ", source1.getColumn("char2").getDirect()[0])
print("Check2a: ", source2.getColumn("char2").getDirect()[0])
print("Check3a: ", source3.getColumn("char2").getDirect()[0])

print("Check0b: ", source.getColumn("char3").getDirect()[0])
print("Check1b: ", source1.getColumn("char3").getDirect()[0])
print("Check2b: ", source2.getColumn("char3").getDirect()[0])
print("Check3b: ", source3.getColumn("char3").getDirect()[0])

print("Check0c: ", ord(source.getColumn("object").getDirect()[1][0]))
print("Check1c: ", ord(source1.getColumn("object").getDirect()[1][0]))
print("Check2c: ", ord(source2.getColumn("object").getDirect()[1][0]))
print("Check3c: ", ord(source3.getColumn("object").getDirect()[1][0]))

meta1 = source1.getMeta()
meta2 = source2.getMeta()
meta3 = source3.getMeta()
```

Unfortunately, the values read back in correspond to the old null value.

**Review by hythloda — APPROVED** [review]

**Comment by chipkent** [comment]
It has been decided that this PR should go in, and the problems with null handling in Parquet will be addressed in #1548.

**Comment by chipkent** [comment]
Resolves #1550.

**Pull request merged**
