### PR TITLE
test: Added reference parquet files and tests for ObjectCodec implementations

### LINKED ISSUE #5767: ObjectCodec implementations should be tested with legacy files (to ensure that we don't break old files without noticing)
A number of our `ObjectCodec` implementations are not currently used by default (for example, `BigDecimalCodec`). We typically have round-trip tests, verifying that they can still write and re-read data correctly. We should also have Parquet-based tests wherein we verify that we can still consume old files correctly, in order to catch cases when we inadvertently change the interpretation of previously-written data and prevent us from breaking support for user files.

### PR DESCRIPTION
**Pull request by malhotrashivam**
Closes #5767

### CODE REVIEW

**Review by rcaudy — COMMENTED** [review]
Looks good. Please add coverage for more `null` cases (easy just to have a `null` for every type), negative values in `BigDecimalCodec`, compact values in `LocalTimeCodec`, and `ExternalizableCodec`.

**Comment by malhotrashivam** [comment]
> Looks good. Please add coverage for more `null` cases (easy just to have a `null` for every type), negative values in `BigDecimalCodec`, compact values in `LocalTimeCodec`, and `ExternalizableCodec`.

- Added null values in columns, but they still don't cover the `null` cases in codec because these values are encoded as parquet nulls and not as null objects. Therefore, we don't hit the `null` case in codec.
- Added negative values in `BigDecimalCodec` and compact values in `LocalTimeCodec`
- `ExternalizableCodec::decode` was already covered in TestCodecColumns.

**Comment by rcaudy** [comment]
> > Looks good. Please add coverage for more `null` cases (easy just to have a `null` for every type), negative values in `BigDecimalCodec`, compact values in `LocalTimeCodec`, and `ExternalizableCodec`.
> 
> * Added null values in columns, but they still don't cover the `null` cases in codec because these values are encoded as parquet nulls and not as null objects. Therefore, we don't hit the `null` case in codec.
> * Added negative values in `BigDecimalCodec` and compact values in `LocalTimeCodec`
> * `ExternalizableCodec::decode` was already covered in TestCodecColumns.

Our legacy Parquet behavior didn't properly encode nulls, right?

**Comment by malhotrashivam** [comment]
I tried regenerating data before my change #4191 but that didn't hit the `null` case in codec too because that issue was only in the primitive types where, for example, we stored `null` value with `NULL_CHAR` or `NULL_INT` instead of parquet nulls.

**Review by rcaudy — APPROVED** [review]

**Pull request merged**
