### PR TITLE
chore: Bump the compiler, runtime, and test runtime version to Java 21

### LINKED ISSUE #3997: Unable to compile with 17
Currently, we are unable to compile a few packages with `-PcompilerVersion=17`:

```
$ ./gradlew hotspot-impl:compileJava clock-impl:compileJava -PcompilerVersion=17
...
> Task :clock-impl:compileJava FAILED
error: exporting a package from system module java.base is not allowed with --release
1 error

> Task :hotspot-impl:compileJava FAILED
error: exporting a package from system module java.management is not allowed with --release
1 error

FAILURE: Build completed with 2 failures.
...
```

There's even a note in these projects that make it look like it _should_ work:

>    // Explicitly set the source compatibility so gradle will invoke javac with `-source 11` instead of `--release`

Will need to investigate more how to properly fix.

### PR DESCRIPTION
**Pull request by devinrsmith**
Fixes #3997

### CODE REVIEW

**Comment by devinrsmith** [comment]
This is currently failing nightlies when run with Java 11 or 17, with the error

`io.deephaven.lang.completion.ChunkerParserTest`

> java.lang.UnsupportedClassVersionError: io/deephaven/lang/completion/AllTokenIterableImpl has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

**Comment by devinrsmith** [comment]
`GroovyCompile` has been updated to fix the `UnsupportedClassVersionError` error.

**Comment by devinrsmith** [comment]
Noted https://github.com/gradle/gradle/issues/18824, https://github.com/gradle/gradle/pull/22449 as links related to `--add-exports` and `--release`.

**Review by niloc132 — COMMENTED** [review]
Only reviewing gradle wiring so far, I'm assuming the new tests make sense on their own

**Review by rcaudy — COMMENTED** [review]
New unit tests LGTM

**Review by niloc132 — APPROVED** [review]

**Pull request merged**
