### PR TITLE
Upgrade to docker compose v2

### LINKED ISSUE #3554: Integrations:composeBuild invalid tag format
@jcferretti found issue recently,

```
$ ./gradlew :Integrations:test-py-deephaven

> Task :proto:proto-backplane-grpc:generateProtobufCreateContainer
Created container with ID 'generateProtobuf-container-2607ab98-4a7c-4c2f-bb23-aaaad5fa7169'.

> Task :Integrations:composeBuild FAILED
invalid tag "8962777808b1b0c3615255132265be2f_integrations_-postgres": invalid reference format
```

This was not readily reproducible on other machines.

For context, the [gradle-docker-compose-plugin](https://github.com/avast/gradle-docker-compose-plugin) calls out to the shell and expects to execute `docker-compose` and @jcferretti was running with https://github.com/docker/compose-switch.

Ultimately, he was able to find a workaround by relying on a custom wrapper instead of compose-switch:

```
$ cat ~/bin/docker-compose 
#!/usr/bin/env sh

exec docker compose --compatibility "$@"
```

Still unsure exactly why the `--compatibility` flag was newly needed. Did `docker compose` have a recent update? Is `compose-switch` not up to date wrt `docker`? This flag was not need a couple months ago when this PR was tested out: https://github.com/deephaven/deephaven-core/pull/3283

Related to https://github.com/avast/gradle-docker-compose-plugin/issues/322

### LINKED ISSUE #5320: Ensure CI works after docker-compose removal from GH ubuntu-22.04
See https://github.com/actions/runner-images/issues/9557

### PR DESCRIPTION
**Pull request by devinrsmith**
This upgrades the gradle-docker-compose-plugin to support docker compose v2 by default. The important release notes are https://github.com/avast/gradle-docker-compose-plugin/releases/tag/0.17.0, although we are updating to the latest 0.17.6. Some manual configuration of dockerCompose was needed to workaround https://github.com/avast/gradle-docker-compose-plugin/issues/393.

Additionally, this upgrades all of our docker-compose.yml files to be proper v2 files by removing the version. The docker compose version is only relevant for docker-compose (v1). See https://docs.docker.com/compose/intro/history/ for clarification. This was discovered based on the warning from the `docker compose` process, which would otherwise warn:

```
> Task :Integrations:composeBuild
time="2024-04-03T12:09:28-07:00" level=warning msg="/home/devin/dev/deephaven/deephaven-core/Integrations/docker-compose.yml: `version` is obsolete"
```

Fixes #3554
Fixes #5320

### CODE REVIEW

**Comment by devinrsmith** [comment]
I've noted release notes / documentation needed. This is mainly wrt the change to docker compose v2 files.

**Comment by devinrsmith** [comment]
It may be time to do a pass on some of the stuff we have in repo, but don't test or run. For example, I don't know if any of the debezium stuff is still valid.

**Comment by devinrsmith** [comment]
> Approved - I'd still like to see an appropriate place to list `you must have docker compose v2 installed` to do development and testing with dhc, either here or in the docs repo.

We do have this in our README:

### Built from source

Users who wish to modify source code and contribute to the project should build Deephaven from source. For complete instructions, see [How to build Deephaven from source](https://deephaven.io/core/docs/how-to-guides/launch-build/).

Building and running Deephaven requires a few software packages.

| Package        | Version                       | OS           | Required/Recommended |
| -------------- | ----------------------------- | ------------ | -------------------- |
| git            | ^2.25.0                       | All          | Required             |
| java           | >=11, <20                     | All          | Required             |
| docker         | ^20.10.8                      | All          | Required             |
| docker compose | ^2                            | All          | Recommended          |
| Windows        | 10 (OS build 20262 or higher) | Only Windows | Required             |
| WSL            | 2                             | Only Windows | Required             |

**Review by rcaudy — APPROVED** [review]

**Comment by deephaven-internal** [comment]
Labels indicate documentation is required. Issues for documentation have been opened:

Community: https://github.com/deephaven/deephaven-docs-community/issues/183

**Pull request merged**
