### PR TITLE
Update pydeephaven for aj/raj

### PR DESCRIPTION
**Pull request by devinrsmith**

### CODE REVIEW

**Comment by devinrsmith** [comment]
This has been tested w/ the unittestst and examples from py/client/README.md

**Review by rcaudy — COMMENTED** [review]
LGTM

**Review by jmao-denver — APPROVED** [review]
LGTM

**Comment by deephaven-internal** [comment]
Labels indicate documentation is required. Issues for documentation have been opened:

How-to: https://github.com/deephaven/deephaven.io/issues/2714
Conceptual: https://github.com/deephaven/deephaven.io/issues/2717
Reference: https://github.com/deephaven/deephaven.io/issues/2716
Blog: https://github.com/deephaven/deephaven.io/issues/2715

**Pull request merged**
