### PR TITLE
Restore totals table support in the JS API

### LINKED ISSUE #3314: JS API support for totals tables
The JS API is capable of producing totals and grand totals tables that update as the user interacts with the underlying table. However, these haven't been updated to use the new grpc aggregation APIs.

### PR DESCRIPTION
**Pull request by niloc132**
Fixes #3314

### CODE REVIEW

**Review by mofojed — COMMENTED** [review]
@niloc132 At a quick glance, how would @emilyhuxng use this for the databar stuff? We can create a totals table, but we can't join it back to the original table. `JsTable.join` expects another `JsTable`, whereas this is a `JsTotalsTable`. Or am I misthinking this?

**Comment by niloc132** [comment]
Good call, I'll work on relaxing that a bit further. Under the hood, a TotalsTable is just a Table, except we don't let you perform certain operations on it that don't make sense.

**Comment by niloc132** [comment]
@emilyhuxng I've added a new interface which will will permit tables and totals tables to be joined to tables and totals tables.

**Comment by niloc132** [comment]
@mofojed this isn't quite ready, but I wanted to discuss two things, see if we can find a way to finalize and ship it:
 * Count doesn't work the same way it did in DHE, which was to append the column name to `__Count`. From playing a bit with DHE, it will then render the count under each selected column (by default, this is "all of them"), but just as "Count". DHC doesn't let the client create a count aggregation on each column, which makes a bit more sense anyway, but the web UI doesn't presently know how to handle that. Do you want to have synthetic columns created to match DHE behavior, or can the UI handle this?
 * Distinct needs to be able to fetch the array of data that ... is distinct for that column - likely to be a big output, and while in DHE we could download it as a large string, in DHC the server will send an array of whatever type it is, which the JS API can't yet handle (but will be fixed in #188, in the near-ish future). Would it be reasonable to disable this in the short term?

**Comment by niloc132** [comment]
Discussed with Ryan, and we could paper over both of these with custom columns (updateview to normalize arrays to string, and rename Count columns to ColA__Count, ColB__Count...), but ideally we wouldnt do too much of this if we can help it.

**Comment by mofojed** [comment]
For the second, I'd prefer custom columns to match DHE behaviour, until we've improved the JS API usage of subscriptions.
For the first, I thought `COUNT` only counted non-null rows or something, but that doesn't seem to be the case. Certain that it's always the same on every column (basically just row count)? I think I'd still like it to behave like DHE, UI wise we'll need to change up a few things if it essentially just applies to the whole table instead.

**Comment by niloc132** [comment]
In column statistics, the Count operation is only non-nulls (as distinct from Size), but not in aggregations (in either dhe or dhc).

**Comment by niloc132** [comment]
Column renaming and toString-ing is complete, plus also removing requested aggregations that don't make sense and the server will reject.

**Review by mofojed — APPROVED** [review]

**Comment by deephaven-internal** [comment]
Labels indicate documentation is required. Issues for documentation have been opened:

How-to: https://github.com/deephaven/deephaven.io/issues/2720
Conceptual: https://github.com/deephaven/deephaven.io/issues/2721
Reference: https://github.com/deephaven/deephaven.io/issues/2719
Blog: https://github.com/deephaven/deephaven.io/issues/2722

**Pull request merged**
