### PR TITLE
Learn library dependencies, no logic

### PR DESCRIPTION
**Pull request by alexpeters1208**
This is the second of two PR's referenced in ticket #1133, containing only the dependencies needed to run the learn examples without any of the library's internal logic.

### CODE REVIEW

**Comment by niloc132** [comment]
While the exact error is probably transient, this shows the problem I was saying we needed to avoid, downloading dozens of copies of tf in order to build:
```
 Collecting tensorflow
  Downloading tensorflow-2.4.2-cp37-cp37m-manylinux2010_x86_64.whl (394.5 MB)
  Downloading tensorflow-2.4.1-cp37-cp37m-manylinux2010_x86_64.whl (394.3 MB)
  Downloading tensorflow-2.4.0-cp37-cp37m-manylinux2010_x86_64.whl (394.7 MB)
  Downloading tensorflow-2.3.4-cp37-cp37m-manylinux2010_x86_64.whl (320.6 MB)
Collecting grpcio>=1.8.6
  Downloading grpcio-1.39.0-cp37-cp37m-manylinux2014_x86_64.whl (4.3 MB)
Collecting tensorflow-estimator<2.4.0,>=2.3.0
  Downloading tensorflow_estimator-2.3.0-py2.py3-none-any.whl (459 kB)
Collecting tensorflow
  Downloading tensorflow-2.3.3-cp37-cp37m-manylinux2010_x86_64.whl (320.5 MB)
  Downloading tensorflow-2.3.2-cp37-cp37m-manylinux2010_x86_64.whl (320.4 MB)
  Downloading tensorflow-2.3.1-cp37-cp37m-manylinux2010_x86_64.whl (320.4 MB)
  Downloading tensorflow-2.3.0-cp37-cp37m-manylinux2010_x86_64.whl (320.4 MB)
  Downloading tensorflow-2.2.3-cp37-cp37m-manylinux2010_x86_64.whl (516.4 MB)
Collecting tensorboard<2.3.0,>=2.2.0
  Downloading tensorboard-2.2.2-py3-none-any.whl (3.0 MB)
Collecting tensorflow-estimator<2.3.0,>=2.2.0
  Downloading tensorflow_estimator-2.2.0-py2.py3-none-any.whl (454 kB)
Collecting tensorflow
  Downloading tensorflow-2.2.2-cp37-cp37m-manylinux2010_x86_64.whl (516.2 MB)
  Downloading tensorflow-2.2.1-cp37-cp37m-manylinux2010_x86_64.whl (516.2 MB)
  Downloading tensorflow-2.2.0-cp37-cp37m-manylinux2010_x86_64.whl (516.2 MB)
  Downloading tensorflow-2.1.4-cp37-cp37m-manylinux2010_x86_64.whl (422.0 MB)
Collecting astor>=0.6.0
  Downloading astor-0.8.1-py2.py3-none-any.whl (27 kB)
Collecting tensorboard<2.2.0,>=2.1.0
  Downloading tensorboard-2.1.1-py3-none-any.whl (3.8 MB)
Collecting keras-preprocessing==1.1.0
  Downloading Keras_Preprocessing-1.1.0-py2.py3-none-any.whl (41 kB)
Collecting tensorflow
  Downloading tensorflow-2.1.3-cp37-cp37m-manylinux2010_x86_64.whl (421.9 MB)
  Downloading tensorflow-2.1.2-cp37-cp37m-manylinux2010_x86_64.whl (421.8 MB)
  Downloading tensorflow-2.1.1-cp37-cp37m-manylinux2010_x86_64.whl (421.8 MB)
  Downloading tensorflow-2.1.0-cp37-cp37m-manylinux2010_x86_64.whl (421.8 MB)
  Downloading tensorflow-2.0.4-cp37-cp37m-manylinux2010_x86_64.whl (86.4 MB)
  ```

**Comment by jjbrosnan** [comment]
Why are we specifying NumPy version 1.10.1?  That's a six year old version.  Version 1.8 is 8 years old.

Specifying TensorFlow with no version means it will install the latest.  That version is 2.6.0.  TensorFlow 2.6.0 expects the NumPy version to be ~=1.19.2 (per TensorFlow's documentation and pipdeptree)

**Review by jmao-denver — COMMENTED** [review]
1. I would prefer that we do not fix the numpy version, especially If the latest works with tensor and pytorch
2. As we noticed before, bringing in  torch, tensor etc. really adds to the build time and increase the footprint quite a bit. I would suggest that making it clear in the README or HOWTO doc that if a user wants to use the learn module, he/she needs to install these modules manually.

**Comment by jjbrosnan** [comment]
Here are Docker image size comparisons before and after adding the following dependencies:

numpy >= 1.19.2
tensorflow
sklearn
torch
torch-summary

Before:

grpc-api image is **746 MB** in size

After:

grpc-api image is **5.29 GB** in size

That's over 4.5 GB bigger.

**Pull request closed without merging**
