### PR TITLE
Use embedded pattern flags instead of exposing via python wrapper

### PR DESCRIPTION
**Pull request by devinrsmith**
Upon digging into how this filter might be exposed over gRPC, it seems like keeping things simpler and relying on the embedded flag expressions is a better choice as it allows the full pattern to be specified by a string. For motivation, some manually invoked filters that the web ui client is currently constructing is using embedded flags:

```ts
filter.invoke(
  'matches',
  dh.FilterValue.ofString(`(?s)(?i).*\\Q${value}\\E.*`)
)
```

This is an example of setting the flags `DOTALL` (?s) and `CASE_INSENSITIVE` (?i), and using literal wrappers `\Q` / `\E`, to search if the column contains `${value}`.

If we find there are certain patterns in the future that need explicit flags, we can add them back in at that time.

Follow-up to #3693

### CODE REVIEW

**Comment by jmao-denver** [comment]
1. do we still need the 'inverted' flag? 
2. should we point to where a user can find the regex lang spec?

**Comment by devinrsmith** [comment]
> 1. do we still need the 'inverted' flag?
> 
>     2. should we point to where a user can find the regex lang spec?

1. Yes, the `invert_pattern` is still meaningful as it's _not_ the same as just notting the filter.

2. I'm not sure what our thoughts are on linking to javadoc from pydoc? I'd be down for it, as opposed to trying to re-write the docs directly in pydoc. A link to https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html seems good?

**Comment by jmao-denver** [comment]
> > 1. do we still need the 'inverted' flag?
> >    
> >    2. should we point to where a user can find the regex lang spec?
> 
> 1. Yes, the `invert_pattern` is still meaningful as it's _not_ the same as just notting the filter.
> 2. I'm not sure what our thoughts are on linking to javadoc from pydoc? I'd be down for it, as opposed to trying to re-write the docs directly in pydoc. A link to https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html seems good?

1. I am not against having the 'invert_pattern' flag, I just thought that regex itself has the ability to specify 'invert pattern'
2. I am fine with having the link in the Python doc string, which would clearly convey that the Java's regex syntax is what we support.

**Review by jmao-denver — APPROVED** [review]
LGTM

**Pull request merged**
