### PR TITLE
Rename and update docs for ObjectService ServerData and ClientData

### PR DESCRIPTION
**Pull request by devinrsmith**

### CODE REVIEW

**Comment by devinrsmith** [comment]
As discussed in https://github.com/deephaven/deephaven-core/pull/4490#discussion_r1333523603

**Comment by devinrsmith** [comment]
I don't think the python client tests are sufficient to ensure this update is valid - it doesn't exercise the messageStream with references for testing. The proposed Echo plugin in #4490 would be a good candidate for the python client to test against.

**Comment by niloc132** [comment]
Don't forget to regenerate the gwt bindings - the JS code for the protos will be generated, so methods will be missing. Smoke testing is possible for the python server and js client with any of the existing plotly/matplotlib stuff, and for the python client with the existing runfunc plugins.

**Comment by devinrsmith** [comment]
I forget how to do the JS code updates...

**Review by rcaudy — COMMENTED** [review]
.

**Review by rcaudy — COMMENTED** [review]
.

**Review by rcaudy — APPROVED** [review]

**Review by jmao-denver — DISMISSED** [review]
LGTM

**Review by rcaudy — APPROVED** [review]

**Review by chipkent — APPROVED** [review]

**Comment by devinrsmith** [comment]
Tested against https://github.com/deephaven/deephaven.io/pull/3175

**Comment by devinrsmith** [comment]
Tested against https://github.com/deephaven/deephaven.io/pull/3087

**Pull request merged**
