### PR TITLE
Fix publication details for shadowed jars

### LINKED ISSUE #5547: JAVA_PUBLIC_SHADOW projects aren't in the bom, and get an unnecessary classifier added
The psk auth plugin is deployed to maven central, as a PUBLIC project, but doesn't appear in the bom

https://search.maven.org/artifact/io.deephaven/deephaven-bom/0.34.3/pom

The deephaven-server project explicitly depends on it in gradle, and the pom _appears_ to depend on it:

https://search.maven.org/artifact/io.deephaven/deephaven-server/0.34.3/pom

However, Gradle deploys the psk dependency to central as packaging=pom, and classifier=all to get the jar itself. This means that the deephaven-server dependency will not have the psk present at runtime as specfied, when loaded from maven central, though it _will_ correctly have it when run from the deephaven-core project itself.

### PR DESCRIPTION
**Pull request by niloc132**
Fixes #5547

### CODE REVIEW

**Comment by niloc132** [comment]
Tested by invoking publishToMavenLocal and confirming that external projects can correctly depend on our jars.

**Review by devinrsmith — APPROVED** [review]
Built pre and post PR with

```
./gradlew bom:generatePomFileForMyPlatformPublication bom:generateMetadataFileForMyPlatformPublication
```

the diffs for `bom/build/publications/myPlatform/module.json` and `bom/build/publications/myPlatform/pom-default.xml` look correct.

**Review by devinrsmith — APPROVED** [review]

**Comment by niloc132** [comment]
Details for documentation: authentication plugins need to be updated so that their URLs do not end in `-all.jar`, but just `.jar` going forward, starting in 0.25 release.

**Comment by deephaven-internal** [comment]
Labels indicate documentation is required. Issues for documentation have been opened:

Community: https://github.com/deephaven/deephaven-docs-community/issues/223

**Pull request merged**
