### PR TITLE
Remove explicit JVM flags around GC

### PR DESCRIPTION
**Pull request by devinrsmith**
We currently bake-in some GC options that would be better left to default JDK ergonomics or the user.

For example, we are currently unable to (easily) change the garbage collector:

```
$ docker run --env "JAVA_OPTS=-XX:+UseZGC" --rm ghcr.io/deephaven/server:0.17.0             
Error occurred during initialization of VM
Multiple garbage collectors selected
```

### CODE REVIEW

**Comment by rcaudy** [comment]
I don't want to change this. I'm willing to introduce a way to disable the settings, but we should have reasonable defaults tuned for a low-latency application.

**Comment by devinrsmith** [comment]
The good news is that G1GC is the default for 11/17. The default MaxGCPauseMillis for G1GC is 200. @rcaudy, are we worried about bumping MaxGCPauseMillis from 100 to 200?

If we think explicitly setting G1GC/100 is really best for the majority of cases, instead of baking these values into the lower layer start script, we could set them at the docker image layer:

```Dockerfile
ENV JAVA_OPTS="-XX:+UseG1GC -XX:MaxGCPauseMillis=100"
```

This would allow them be wholly overridden when necessary.

**Comment by devinrsmith** [comment]
https://docs.oracle.com/en/java/javase/17/gctuning/garbage-first-garbage-collector-tuning.html#GUID-0BB3B742-A985-4D5E-A9C5-433A127FE0F6

https://docs.oracle.com/en/java/javase/17/gctuning/garbage-first-garbage-collector-tuning.html#GUID-4914A8D4-DE41-4250-B68E-816B58D4E278

is relevant material.

**Comment by devinrsmith** [comment]
It's reasonable for us to consider removing the explicit `-Xmx4g` from example compose files; and potentially add `-XX:MaxRAMPercentage=70.0` (instead of the default 25.0) as part of `JAVA_OPTS`.

**Comment by rcaudy** [comment]
You need to have local runs pick up the options as well (START_OPTS and JAVA_OPTS).

**Review by rcaudy — APPROVED** [review]

**Comment by deephaven-internal** [comment]
Labels indicate documentation is required. Issues for documentation have been opened:

How-to: https://github.com/deephaven/deephaven.io/issues/1839
Conceptual: https://github.com/deephaven/deephaven.io/issues/1837
Reference: https://github.com/deephaven/deephaven.io/issues/1840
Blog: https://github.com/deephaven/deephaven.io/issues/1838

**Pull request merged**
