### PR TITLE
feat: Add iframe/widget endpoint for displaying widgets

### PR DESCRIPTION
**Pull request by mofojed**
- Opens widgets from plugins (such as plotly-express) or any table just by name by adding the iframe/widget path
- Exposed at `/iframe/widget`
- Updated workflow to automatically update the version when new web packages are published
- Tested by running the following code to create a plotly-express widget and some tables:
```
import deephaven.plot.express as dx
from deephaven import time_table
import random
import pandas as pd
import deephaven.pandas as dhpd

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/earthquakes-23k.csv')

t = dhpd.to_table(df)

sourceh = time_table("PT1S").update(formulas=[
    "X = (int)random.uniform(0, 180) - 90",
    "Y = (int)random.uniform(0, 360) - 180",
    "Z = (float)random.gauss(30, 3)",
    "l1 = i % 20",
    "l2 = i % 30",
    ])

fig = dx.density_mapbox(t,  lat='Latitude', lon='Longitude', z='Magnitude', radius=10,
                        center=dict(lat=0, lon=180), zoom=0,
                        mapbox_style="stamen-terrain")
```
- Then tested that each table/widget opened correctly by opening the following links:
1. plot.express: http://localhost:10000/iframe/widget/?name=fig
2. table: http://localhost:10000/iframe/widget/?name=t
3. Pandas data frame: http://localhost:10000/iframe/widget/?name=df

### CODE REVIEW

**Review by devinrsmith — DISMISSED** [review]
Is the plan to deprecate / remove `/iframe/chart/` / `/iframe/table/`?

**Comment by mofojed** [comment]
Need to add an example to the iframe documentation: https://deephaven.io/core/docs/how-to-guides/use-iframes/#display-tables-in-an-iframe

**Review by dsmmcken — DISMISSED** [review]
Yes, we should deprecate the table and chart paths, but only once we have proper code splitting for bundle size based on what's loaded.

**Review by dsmmcken — APPROVED** [review]

**Review by devinrsmith — APPROVED** [review]

**Comment by deephaven-internal** [comment]
Labels indicate documentation is required. Issues for documentation have been opened:

How-to: https://github.com/deephaven/deephaven.io/issues/3551
Reference: https://github.com/deephaven/deephaven.io/issues/3552

**Pull request merged**
